---
abstract: 'Adds LastTransactionContent as a search display column'
author:
  - '-2014 by Best Practical Solutions.'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-TicketlistTransactions
no_index:
  directory:
    - html
    - inc
requires:
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.03
